# Generated by Django 3.1.2 on 2020-12-08 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan', '0009_delete_suggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(1, 'waiting'), (2, 'denied'), (3, 'approved')])),
                ('hashtag', models.ManyToManyField(related_name='suggestion_hashtag', to='plan.HashTag')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_place', to='plan.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
