# Generated by Django 3.1.2 on 2020-11-14 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_personalitytestquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification_type', models.CharField(max_length=30)),
                ('personality_type', models.CharField(choices=[('O', 'openness'), ('C', 'conscientiousness'), ('E', 'extraversion'), ('A', 'agreeableness'), ('N', 'neuroticism')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='personalitytestquestion',
            name='weight',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalities', to='account.personalitytype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personality', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personalitytestquestion',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='account.personalitytype'),
        ),
    ]
