# Generated by Django 3.1.2 on 2020-11-07 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag_name', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hashtag_feature', to='plan.features')),
            ],
        ),
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('status', models.IntegerField()),
                ('avg_score', models.FloatField()),
                ('features', models.ManyToManyField(blank=True, related_name='place_feature', to='plan.Features')),
            ],
        ),
        migrations.CreateModel(
            name='Taxi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=32)),
                ('car_number', models.CharField(max_length=15)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='TransportationReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=64)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('head_count', models.IntegerField()),
                ('tot_price', models.IntegerField()),
                ('taxi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_taxi', to='plan.taxi')),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=32)),
                ('status', models.IntegerField()),
                ('hashtag', models.ManyToManyField(related_name='suggestion_hashtag', to='plan.HashTag')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_place', to='plan.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('content', models.TextField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_place', to='plan.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('feature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preference_feature', to='plan.features')),
                ('personality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preference_personality', to='plan.personality')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('feedback', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_name', models.CharField(max_length=64)),
                ('reservation_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField()),
                ('head_count', models.IntegerField()),
                ('tot_price', models.IntegerField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_place', to='plan.place')),
            ],
        ),
        migrations.CreateModel(
            name='Instagram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('hashtags', models.ManyToManyField(related_name='instagram_hashtag', to='plan.HashTag')),
            ],
        ),
        migrations.CreateModel(
            name='HalfDayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_activity', to='plan.placereservation')),
                ('dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_dinner', to='plan.placereservation')),
                ('scenary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_scenary', to='plan.placereservation')),
                ('transportation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_trans', to='plan.transportationreservation')),
            ],
        ),
    ]
