# Generated by Django 3.1.2 on 2020-11-08 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20201107_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_plan', to='plan.plan'),
        ),
    ]
