# Generated by Django 3.1.2 on 2020-11-14 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20201114_0639'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalfDayOffReservation',
            fields=[
                ('plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reservation', serialize=False, to='plan.plan')),
                ('activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_activity', to='plan.placereservation')),
                ('dinner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_dinner', to='plan.placereservation')),
                ('scenary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_scenary', to='plan.placereservation')),
            ],
        ),
        migrations.AddField(
            model_name='taxi',
            name='reservable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transportationreservation',
            name='status',
            field=models.IntegerField(choices=[(1, 'not_reserved'), (2, 'reserved'), (3, 'finish')]),
        ),
        migrations.DeleteModel(
            name='HalfDayOff',
        ),
        migrations.AddField(
            model_name='halfdayoffreservation',
            name='transportation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='halfdayoff_trans', to='plan.transportationreservation'),
        ),
    ]
