# Generated by Django 3.1.2 on 2020-12-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0007_auto_20201127_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='status',
            field=models.IntegerField(choices=[(1, 'waiting'), (2, 'denied'), (3, 'approved')]),
        ),
    ]
