# Generated by Django 3.1.2 on 2020-12-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0008_auto_20201208_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Suggestion',
        ),
    ]
