# Generated by Django 3.1.2 on 2020-12-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0009_delete_suggestion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='image_urls',
        ),
        migrations.AddField(
            model_name='place',
            name='image_key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='roadAddress',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='status',
            field=models.IntegerField(choices=[(1, 'suggested'), (2, 'verified'), (3, 'denied')]),
        ),
    ]
