# Generated by Django 3.1.2 on 2020-12-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0010_auto_20201209_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='extraAddress',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
