# Generated by Django 3.1.2 on 2020-12-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0011_place_extraaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='count',
        ),
    ]
