# Generated by Django 3.1.2 on 2020-12-16 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0012_remove_hashtag_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='total_distance',
            field=models.IntegerField(null=True),
        ),
    ]
